### ISSUE TITLE
Empty Folder

### ISSUE THREAD

**Issue by ghost** [ultimate-pms/fake-video-detector#1]
The libpuzzle folder is empty causing setup.sh to display the error below:

> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat fake-video-detector/libpuzzle-docker/Dockerfile: no such file or directory

**Comment by ned-kelly** [comment]
The project uses submodules, can you try cloning with: `git clone --recurse-submodules https://github.com/ultimate-pms/fake-video-detector.git`. I've also included the last stable release of libpuzzle (since it's no longer actively developed), so if you do a pull it should also be there.
